[package]
name = "chennai-house-prices-desktop"
version = "0.1.0"
description = "Tamil Nadu Property Price Predictor desktop app"
authors = ["runeking2006"]
license = "MIT"
repository = "https://github.com/runeking2006/chennai-house-prices"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
tauri = { version = "2.11.5", features = [] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
